Milestone 2
M20Jay/Portfolio-setup-and-mobile-first pull request #1
Opened 2022-11-04 16:38 UTC by M20Jay

Add html files
Edit css files
Style header
Run linters error checks

2022-11-04 18:45 UTC, Tadesse-Alemayehu requested changes
### Hi @M20Jay 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![199733072-bdacca19-8df9-43a7-be93-3aff2f1c15c8](https://user-images.githubusercontent.com/69077061/200051383-6ecda581-e432-46ce-844b-8e7b4cfd8db5.gif)

## Highlights
 - [ ] Good job overall following the template design 💯
 - [ ]  Correct GitHub Flow 👍🏾
 - [ ]  Good commit history 🥇
 - [ ]  Good PR title/description 💯
 - [ ]  All linters passed 🥇
 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 18:45 UTC, Tadesse-Alemayehu commented on style.css
>  }
- [ ] Dear @M20Jay I see you use the `heading` class to style your `toolbar`, Instead, you should use the `header ` tag to wrap your `toolbar` content. Also, you use `header` tags to wrap all your content (both `toolbar` and `headline` sections). this will make your website semantically poor. Please use `header`  to wrap only the toolbars. 
- [ ] Also the `header` should be aligned with flexbox `display: flex;`.
![toolbar](https://user-images.githubusercontent.com/69077061/200047700-90adbf9b-8552-4f91-9107-792606863830.PNG)

2022-11-04 18:45 UTC, Tadesse-Alemayehu commented on style.css
>  }
- [ ] Dear @M20Jay, Your design is fantastic, Yet Adding some modifications will make it perfect. so, Both sections should have the margins (top, bottom, left, right) defined in the design. 

### This is how it reacts on the `375px` screen right now. 
![your-dsign-375](https://user-images.githubusercontent.com/69077061/200050112-021b3701-5c6f-4ad0-8b7b-85c14fc3ae92.png)

### This is how It should look like
![your](https://user-images.githubusercontent.com/69077061/200050312-48141c81-601b-4058-bad0-c4f6e28a04ca.png)

2022-11-04 18:50 UTC, M20Jay commented on style.css
>  }
[Tadesse-Alemaye](https://github.com/Tadesse-Alemayehu) thank you so much for your compliments and feedback.
Kindly I will appreciate your help in this. Cab we connect via zoom? I am not sure I got all the points.

2022-11-04 19:05 UTC, Tadesse-Alemayehu commented on style.css
>  }
- Dear @M20Jay, I would love that, but I don't think I have the time right now, If you have other tasks to go through for today you should go for that now and we can schedule for tomorrow. If not I'll suggest you try your best and if you still can't make it we defiantly will address it tomorrow. 👍

2022-11-04 20:37 UTC, Felix45 requested changes
Hi @M20Jay , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: 

You have submitted a project, that has failed linter checks. Please fix the stylelint linter errors and submit for a new code review. Most of the linter errors you are experiencing can be fixed by the command below  in your terminal :pray: 

`npx stylelint "**/*.{css,scss} --fix"`

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-11-04 20:42 UTC, M20Jay commented
[Felix45](https://github.com/Felix45) your reviews sometimes are confusing. I had everything right until someone called to confuse me. Now I am repeating the codes that were all accurate and had been passed by the first reviewer. It is frustrating when I get it right the first time and some mislead me again

2022-11-04 20:56 UTC, M20Jay commented
[Felix45](https://github.com/Felix45) it is not fair at all. I am frustrated after all the work someone ruins everything, Check the reviewer the first reviewer.

2022-11-04 22:02 UTC, jaflih requested changes
Hi @M20Jay , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
Good job overall following the template design 💯
 Correct GitHub Flow 👍🏾
 Good commit history 🥇
 Good PR title/description 💯
 All linters passed 🥇

 ## Required Changes ♻️
_Check the comments under the review._

- Please implement all requested changes asked by the first reviewer
- Please don't ask for a new review while you have linters errors ( asked by the second reviewer) 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @jaflih in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-05 20:49 UTC, Owusu-Desmond approved these changes
Hi @M20Jay , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the set up the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-05 20:54 UTC, merged

2022-11-05 20:55 UTC, M20Jay commented
[Owusu-Desmond](https://github.com/Owusu-Desmond) Thank you.

2022-12-01 13:33 UTC, andgarzonmal reviewed
Hi @M20Jay , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- No linter errors ✔️ 
- Good implementations  ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._